FROM golang:alpine as builder
RUN mkdir /build 
ADD . /build/
WORKDIR /build 
RUN rm -rf /var/cache/apk/* && \
    rm -rf /tmp/*
RUN apk update
RUN apk add git gcc musl-dev bash
RUN go get -d -v
RUN go build -o main .
FROM alpine:latest
COPY --from=builder /build/main /app/
EXPOSE 8000
WORKDIR /app
CMD ["./main"]